import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Your Bank - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.svg" sizes="any" />
      </head>
      <body className={inter.className + ' bg-[#1e1e1e] py-10 px-6 md:px-20 xl:px-36'}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
