import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Your Bank - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" href="/icon.svg" sizes="any" />
      </head>
      <body className={inter.className + ' bg-white-4 text-grey-950 dark:bg-grey-950 dark:text-white transition-colors duration-300 py-10 px-6 md:px-20 xl:px-36 min-h-screen flex flex-col justify-between'}>
        <div>
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
